### ISSUE TITLE
Step 5 does not stop if file not exist

### ISSUE THREAD

**Issue by ArthurNguyen** [mscheltienne/eeg-flow#22]
https://github.com/mscheltienne/eeg-flow/blob/806dcc199e809dc65001897621445f5276b36af2/eeg_flow/tasks/ica_decomposition.py#L343C5-L343C30

Hello, 
There's an error here in the step 5, inside of eeg_flow.tasks.label_components

If attempting to open a file where the deratives of step 4 does not exist we expect this behavior: 
- output: "error, this file does not exist"

What we have instead:
- The code seems to continue until it is stuck with this error "Channel CPz already specified in inst."

![WhatsApp Image 2023-09-01 at 13 28 06](https://github.com/mscheltienne/eeg-flow/assets/7384580/3c597c20-9f68-49b3-b693-2951a58a90dd)
![WhatsApp Image 2023-09-01 at 13 28 07](https://github.com/mscheltienne/eeg-flow/assets/7384580/9e11697c-68fc-4b64-b39f-13b65a2fc9a1)

**Comment by mscheltienne** [comment]
It first load the step3 file before loading the step4:

https://github.com/mscheltienne/eeg-flow/blob/806dcc199e809dc65001897621445f5276b36af2/eeg_flow/tasks/ica_decomposition.py#L266-L272

Thus, it doesn't get a `FileNotFoundError` because we never reach the loading of the step 4 files. That still does not explain why we are failing to load the step 3 file. I suspect something else is wrong with that file and it should be investigated and understood. Can you load the `derivatives_folder / f"{fname_stem}_step3_with-bads_raw.fif"` file with `mne.io.read_raw_fif` and check:

- The values in `raw.info["highpass"]` and `raw.info["lowpass"]` 
- The channels names, `raw.info["ch_names"]` which should not include `CPz`
